---
triple:          'arm64-apple-darwin'
binary-path:     stack
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _stackFunc, symObjAddr: 0x0, symBinAddr: 0x100003EDC, symSize: 0x50 }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _stackFunc, symObjAddr: 0x0, symBinAddr: 0x100003EDC, symSize: 0x50 }
  - { offsetInCU: 0x77, offset: 0x77, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x50, symBinAddr: 0x100003F2C, symSize: 0x50 }
...
